# Generated by Django 4.0.6 on 2022-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='businesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(max_length=50)),
                ('street2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('parish', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('tax_registration_number', models.CharField(max_length=50)),
                ('national_insurnce_scheme', models.CharField(max_length=50)),
                ('business_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='company_banking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField()),
                ('account_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('account_number', models.IntegerField(max_length=30)),
                ('account_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('deduction_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('earning_type', models.CharField(max_length=50)),
                ('PTD_amount', models.IntegerField()),
                ('taxable', models.CharField(max_length=50)),
                ('pay_frequency', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('work_address', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('TRN', models.IntegerField()),
                ('NIS', models.IntegerField()),
                ('contact_number', models.IntegerField(max_length=30)),
                ('personal_email_address', models.EmailField(max_length=254)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('contact_number_of_next_of_kin', models.IntegerField(max_length=30)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=50)),
                ('city_town', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('parish', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee_banking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pay_frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField()),
                ('pay_frequency', models.CharField(max_length=50)),
                ('number_of_periods', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pay_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField()),
                ('pay_frequency_id', models.IntegerField()),
                ('pay_frequency', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('payment_term', models.CharField(max_length=50)),
            ],
        ),
    ]
